Update and rename pi-app-manager to paper-town-onestep

diff --git a/usr/bin/paper-town-onestep b/usr/bin/paper-town-onestep
--- a/usr/bin/paper-town-onestep
+++ b/usr/bin/paper-town-onestep
@@ -9,6 +9,7 @@
 # Email : shun819.mail@gmail.com
 
 # Pi-App-Manager based Serene-Startdash
+# PaperTown-Onestep
 # PianoCat 2020.
 # Twitter: @nsk_id1010
 # Email : kotone.olin1010@gmail.com
@@ -33,9 +34,9 @@
 
 
 #-- 設定 --#
-settings=/etc/pi-app-manager/config
+settings=/etc/serene-startdash/config
 entry_extension="entry"
-version=1.00-1
+version=1.10-2
 
 
 
@@ -207,8 +208,8 @@ function show_version () {
         --info \
         --width="600" \
         --height="100" \
-        --text="＝＝　Pi-App-Manager　＝＝\nVersion:　${version}\nPianoCat kotone.olin1010@gmail.com"
-    debug_msg "Pi-App-Manager v${version}"
+        --text="＝＝　PaperTown-Onestep　＝＝\nVersion:　${version}\nPianoCat kotone.olin1010@gmail.com"
+    debug_msg "PaperTown-Onestep v${version}"
     exit 0
 }
 
@@ -240,6 +241,24 @@ make_installed_list () { ${pacman} -Q | awk '{print $2}' > /tmp/installed_list ;
 installed_list () { cat /tmp/installed_list ;}
 remove_installed_list () { rm -rf /tmp/installed_list ;}
 
+#-- check_snapについて --#
+function isinstalled_snap () { 
+    if [[ "$(check_pkg snapd)" == installed_apt ]]; then
+	    snapd=installed
+    else
+	printf "cannot_get_install_status"
+    fi
+}
+
+function installed_snap_list () {
+    if [[ "$snapd" == installed ]]; then
+        snap list | awk 'NR>1 {print $1}'
+    else
+	printf "canot_get_install_status"
+    fi
+}
+
+
 #-- set false --#
 set +eu
 [[ ! $recall = true ]] && recall=false
@@ -263,7 +282,7 @@ function install_and_uninstall () {
     set + eu
     if [[ -n $softwares_update && -f $softwares_update && -x $softwares_update ]]; then
         $softwares_update | loading 600 100 "スクリプトを更新しています。"
-        if [[ -z $(ls /etc/pi-app-manager/softwares 2> /dev/null) ]]; then
+        if [[ -z $(ls /etc/serene-startdash/softwares 2> /dev/null) ]]; then
             error 500 100 "スクリプトのアップデートに失敗しました。"
             exit 1
         fi
@@ -309,8 +328,18 @@ function install_and_uninstall () {
         clear_variable
     done
 
-    
+    # snapパッケージのアンインストール
+    function uninstall_snap () {
+        snap remove $name
+    }
+
+
+
     # リスト
+    # 高速化のためにここでsnapdがインストールされているか判定する
+   isinstalled_snap
+   make_installed_list
+
     window \
         --warning \
         --width="600" \
@@ -443,6 +472,18 @@ function install_and_uninstall () {
                     --height=100
                 uninstall | loading 600 100 "パッケージ$nameをアンインストールしています。"
                 set +eu
+	    elif [[ $(check_snap $package_name) == installed_snap ]]; then
+	        set -eu
+		window \
+		    --question \
+		    --text="パッケージ$nameはsnapパッケージでインストール済みです。debパッケージに置き換えます。よろしいですか？" \
+		    --ok-label="続行する" \
+		    --cancel-label="中断する" \
+		    --width=600 \
+		    --height=100
+		uninstall_snap | loading 600 100 "パッケージ$nameをアンインストールしています。"
+		install | loading 600 100 "パッケージ$nameをインストールしています"
+		set +eu
             fi
         fi
         set -eu
@@ -461,7 +502,7 @@ if [[ ! $direct_execution = true ]]; then
     run=$(
         window \
             --info \
-            --text="何を実行しますか？\n\n終了・・・終了します$( if [[ -n $softwares_update && -f $softwares_update && -x $softwares_update ]]; then echo "\n一覧をアップデート・・・「追加と削除」で選択できる項目をアップデートします。"; fi )\nクリーンアップ・・・パッケージのクリーンアップを行います。\nアップグレード・・・パッケージのアップグレードを行います\nアップデート・・・パッケージリストのアップデートを行います。\n追加と削除・・・パッケージのインストールやアンインストールを行います。 " \
+            --text="何を実行しますか？\n\n終了・・・終了します$( if [[ -n $softwares_update && -f $softwares_update && -x $softwares_update ]]; then echo "\n一覧をアップデート・・・「追加と削除」で選択できる項目をアップデートします。"; fi )\nクリーンアップ・・・パッケージのクリーンアップを行います。\nアップグレード・・・パッケージのアップグレードを行います\nアップデート・・・APTパッケージリストのアップデートを行います\n追加と削除・・・パッケージのインストールやアンインストールを行います。 " \
             --ok-label="終了する" \
             $(
                 # スクリプトのアップデート
@@ -490,7 +531,7 @@ case $run in
     "追加と削除" ) install_and_uninstall ;;
     "アップグレード" ) $pacman -Syu --noconfirm | loading 600 100 "パッケージのアップグレードを行っています。" ;;
     "クリーンアップ" ) cleanup ;;
-    "アップデート" ) $apt update | loading 600 10. "パッケージリストのアップデートを行っています。" ;;
+    "アップデート" ) $sudo apt update | loading 600 100 "APTパッケージリストのアップデートを行っています。"
     "一覧をアップデート" ) $softwares_update | loading 600 100 "スクリプトを更新しています。";;
     * ) error 600 100 "例外が発生しました。"; exit 1;;
 esac
